name: TruffleHog Enterprise scan

on: [push, pull_request]

jobs:
  scanning:
    name: TruffleHog Enterprise scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Running Trufflehog scan
        run: |
            docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --max-depth 10 --only-verified --fail
            echo "Docker Done"
            if: always()
      - name: Notify dedicated teams channel for secrets
        if: failure()
        run: |
            echo "Secrets found"
      - name: Notify dedicated teams channel for secrets not found
        if: success()
        run: | 
            echo "No Secrets Found"
            exit 0
